### ISSUE TITLE
GUI horizontal box not large enough for text

### ISSUE THREAD

**Issue by StefaanVerwimp** [gamcil/cblaster#39]
Would it be possible to change the horizontal size of the gui, or to make it resizable?

![image](https://user-images.githubusercontent.com/59533725/111006710-94805d80-838d-11eb-899b-e519a80c8598.png)
(running Pop_OS)

**Comment by gamcil** [comment]
Oh weird, I haven't run into this before across the OS's we've tested (Windows/Mac/Ubuntu/openSUSE). Unfortunately the GUI library we use is mainly built for completely static size applications (https://github.com/PySimpleGUI/PySimpleGUI/issues/2004) making resizing pretty fiddly to try and implement. A PyQt version of the GUI is in the works which will fix this altogether.

In the meantime, it looks like it's failing to find a font on your system. Some elements specify Arial which I'm guessing Pop OS doesn't come with due to licensing. Could you try installing `ttf-mscorefonts-installer` and see if that fixes it?

**Comment by StefaanVerwimp** [comment]
I already had `ttf-mscorefonts-installer` installed, even after purging and reinstalling, the problem persists. Refreshing the font cache also didn't help. But this is might a problem on my part, I'm pretty new to linux and I probably messed something up while configuring my system.
